### ISSUE TITLE
Synth is broken

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-os-login#273]
I am running through and trying to GA libraries, and noticed that `synth` has been broken here for a bit.  There is a command here:
https://github.com/googleapis/nodejs-os-login/blob/master/synth.py#L51

```
subprocess.run(['npm', 'compileProtos', 'src'])
```

That is not a valid `npm` command.  Thinking you want:

```
subprocess.run(['npm', 'run', 'compile-protos'])
```

Even after making that change, I am getting an error:

```
> @google-cloud/os-login@1.3.2 compile-protos /Users/beckwith/Code/nodejs-os-login
> compileProtos src

(node:83080) UnhandledPromiseRejectionWarning: Error: illegal token 'option' (protos/google/cloud/oslogin/common/common.proto, line 107)
    at illegal (/Users/beckwith/Code/nodejs-os-login/node_modules/protobufjs/src/parse.js:94:16)
    at parse (/Users/beckwith/Code/nodejs-os-login/node_modules/protobufjs/src/parse.js:719:27)
    at process (/Users/beckwith/Code/nodejs-os-login/node_modules/protobufjs/src/root.js:107:30)
    at fetch (/Users/beckwith/Code/nodejs-os-login/node_modules/protobufjs/src/root.js:166:13)
    at Root.load (/Users/beckwith/Code/nodejs-os-login/node_modules/protobufjs/src/root.js:194:13)
    at Root.loadSync (/Users/beckwith/Code/nodejs-os-login/node_modules/protobufjs/src/root.js:235:17)
    at main (/Users/beckwith/Code/nodejs-os-login/node_modules/protobufjs/cli/pbjs.js:236:18)
    at internal/util.js:278:30
    at new Promise (<anonymous>)
    at main (internal/util.js:277:12)
(node:83080) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:83080) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

This is blocking auto-generation and GA, so P1'in it

**Comment by alexander-fenster** [comment]
We actually want `npx compileProtos src` (`npx`, not `npm`). I'll just grep all the repos and fix it. Seems like we might have a bad example somewhere.

**Comment by alexander-fenster** [comment]
@JustinBeckwith But it indeed fails because of https://github.com/protobufjs/protobuf.js/pull/1183 - my first (and only so far) PR in protobuf.js. Merged in April and still not released :)  Ever wondered why I'm pessimistic about it? This is exactly why.

I will submit a proto fix to move the option to the beginning of the file.
